###################################
#running a PET image reconstruction in castor
#df -> castor header (.Cdh) file corresponding to the data file (.Cdf, which MUST have the same name)
#dim -> image dimensions
#vox -> voxel dimesnion
#dout -> directory, where the reconstructed images will be saved 
#sens -> sensitivity map of the phantom (in my case generated by sens_map.sh in this directory) 
##################################


phantomPath=/home/jpet/ccb_dane/sens_map_dualhead/sens_map_dualhead_it1.hdr

castor-recon -df /home/jpet/ccb_dane/offbeam_plexa/DJ_2021.10.24_0003_merged.Cdh -dim 160,160,200 -vox 2.5,2.5,2.5 -th 0 -it 5:1 -dout /home/jpet/ccb_dane/offbeam_plexa/plexi_recoim_v2 -ignore-corr fdur -sens $phantomPath -proj multiSiddon,10,1 -vb 2



